export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL'
export const ADD_CART = 'ADD_CART'
export const DELETE_CART = 'DELETE_CART'
export const FILTER = 'FILTER'
